### ISSUE TITLE
[BUG] AddressNotFound: account not found on-chain

### ISSUE THREAD

**Issue by Drabuna** [bitcart/bitcart#336]
**Describe the bug**
I've created 2 hot wallets TRX (USDT). 
Received some money on one of them.
Now I'm trying to do a payout from one to another (or to a different address).
After `send`, the status becomes `failed`, and I get the following error in the log:

```
2023-03-05 16:59:03,721 - [PID 46] - api.crud.payouts.batch_payout_action [line 47] - ERROR - 
Traceback (most recent call last):
  File "/app/api/crud/payouts.py", line 45, in batch_payout_action
    await payouts_ext.send_payout(payout, private_key=wallets.get(payout.wallet_id))
  File "/app/api/ext/payouts.py", line 100, in send_payout
    tx_hash = await broadcast_tx_flow(coin, wallet, raw_tx, payout.max_fee, divisibility, rate)
  File "/app/api/ext/payouts.py", line 110, in broadcast_tx_flow
    predicted_fee = Decimal(await coin.server.get_default_fee(raw_tx))
  File "/usr/local/lib/python3.9/site-packages/bitcart/providers/jsonrpcrequests.py", line 132, in wrapper
    raise UnknownError(f"Unknown error from server: {message}")
bitcart.errors.UnknownError: Unknown error from server: tronpy.exceptions.AddressNotFound: account not found on-chain
```

**Expected behavior**
Should work.

**Comment by Drabuna** [comment]
Could be related to wallet activation, but I'm not sure if it's done automatically in bitcart, or I have to do it myself.
Help would be appreciated :)

**Comment by MrNaif2018** [comment]
It's tron network specifics. I think I have fixed the issue before, but re-checking now

**Comment by MrNaif2018** [comment]
I was able to send both transactions to fresh accounts on nile testnet without problem

**Comment by Drabuna** [comment]
Hm. Still a problem for me. I've sent some TRX to my wallet, so it's now "activated".
I can see through admin UI that I have some money there that I sent earlier (TRC-20).
Through tronscan.org I can only see TRX amount, not TRC-20 amount.
Bitcart shows the TRC-20 amount, but not the TRX amount.
When I try to send a payout, I still get the same error.
Thoughts, ideas?

**Comment by MrNaif2018** [comment]
Is it on mainnet tron? Maybe it has different rules, I can test if so
Bitcart shows balance for a wallet based on the currency field. If it's set, it shows this contract balance. If it isn't set, it shows TRX balance

**Comment by Drabuna** [comment]
Yeah, mainnet Tron.

**Comment by Drabuna** [comment]
OK, this was an issue with activation. So you have to "activate" the wallet by transferring some TRX/TRC-10 to it before you can do payouts.

**Comment by MrNaif2018** [comment]
Well it's still a bug I think, I will re-verify and close it if it works as I expect
Like the fee estimation func should still work even if address is not activated I think

**Comment by MrNaif2018** [comment]
Re-verified

The issue only occurs if you try to send USDT when you have never had tron on an account. I tried fixing it, but then you get error message when broadcasting anyway which isn't any better. I will leave it this way, but maybe in the future we could hint the user that the address can't send usdt without trx
